<?php

namespace Modules\Vote\Transformers\Api\Admin;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Collection;

class ApiAdminVoteItemResource extends JsonResource
{
    private static array $_data = [];

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return collect($this->resource)->when(array_key_exists('users_count',$this->resource->toArray()) && array_key_exists('item_users_count', $this->additional), function (Collection $collection) {
            $collection->put('percent', $this->resource->getPercentOfTotal($this->resource->users_count, $this->additional['item_users_count']));
        });
    }

    public function __construct($resource)
    {
        $this->additional(self::getData());
        parent::__construct($resource);
    }

    public static function collection($resource, $data = [])
    {
        self::setData($data);
        return parent::collection($resource); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public static function getData(): array
    {
        return self::$_data;
    }

    /**
     * @param array $data
     */
    public static function setData(array $data): void
    {
        self::$_data = $data;
    }

}
